model_path: "./scripts/neural_rendering/logs/dtu_training"
cuda: 0
center: [0.0, 0.3, 0.4]
radius: 0.3887
# 定义角度范围（单位：度）
phi_steps: 10     # 水平角（方位角）
theta_steps: 10              # 垂直角（极角）
up: [0, 0, 1]                             #指示世界坐标的上方向
budget: 20
focal: [723.0826, 720.7939]
c: [205.8013, 154.7675]
z_near: 0.1
z_far: 3.5