name: neural_rendering
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.9
  - pip
  - pip:
      - pyhocon
      - opencv-python
      - dotmap
      - tensorboard
      - imageio
      - imageio-ffmpeg
      - ipdb
      - pretrainedmodels
      - lpips
      - torchmetrics
      - torchinfo
      - click
      - torch-tb-profiler
      - matplotlib
      - seaborn
      - pandas
  - scipy
  - numpy
  - pytorch==1.12.0
  - torchvision==0.13.0
  - scikit-image==0.17.2
  - tqdm
